version: "3.8"
services:
  api:
    image: node:16-alpine3.12
    volumes:
      - ./backend:/app
      - ./shared:/shared
    working_dir: /app
    command: yarn start:dev
    ports:
      - "3001:3001"
  web:
    image: node:16-alpine3.12
    volumes:
      - ./frontend:/app
      - ./shared:/shared
    working_dir: /app
    command: sh -c "npm rebuild esbuild && yarn dev"
    ports:
      - "3000:3000"
