version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
  api:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    command: yarn start:dev
    ports:
      - "3001:3001"
